FROM grafana/grafana:8.2.6

COPY ./provisioning/datasources /etc/grafana/provisioning/datasources
COPY ./provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY ./dashboards /var/lib/grafana/dashboards
