interface = udp::0.0.0.0:4789:vxlan
# interface = af_packet::eth0

workers = 4
loggers = 1
proxies = 2
workers_cpu_list = 0-8:2

worker_memory_max = 512M
logger_memory_max = 512M
proxy_memory_max = 512M
manager_emory_max = 512M

metrics_address = 0.0.0.0
