{
 "title": "Zeek Logs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "conn.log",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"conn.log\"} | json"
    }
   ]
  },
  {
   "title": "dns.log",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"dns.log\"} | json"
    }
   ]
  },
  {
   "title": "ssl.log",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"ssl.log\"} |  json "
    }
   ]
  },
  {
   "title": "http.log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"http.log\"} | json"
    }
   ]
  }
 ]
}