{
 "title": "Zeek DNS",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "DNS Answer Count Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zeek_dns_ancount_total_bucket", "legendFormat": "{{ le }}" }
   ]
  },
  {
   "title": "DNS Question Count Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zeek_dns_qdcount_total_bucket", "legendFormat": "{{ le }}" }
   ]
  },
  {
   "title": "DNS Answer Count Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(zeek_dns_ancount_total_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DNS Question Count Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(zeek_dns_qdcount_total_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}