{
 "title": "Zeek Telemetry",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"zeek\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"zeek\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Monitoring Traffic Bytes and Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(zeek_bytes_received_total[$__rate_interval])",
     "legendFormat": "bytes received"
    },
    {
     "expr": "rate(zeek_packets_received_total[$__rate_interval])",
     "legendFormat": "packets received"
    },
    {
     "expr": "rate(zeek_packets_dropped_total[$__rate_interval])",
     "legendFormat": "packets dropped"
    }
   ]
  },
  {
   "title": "Log Writes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(zeek_log_writes_total{}[$__interval])",
     "legendFormat": "{{ log_id }}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "zeek_active_sessions", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Sessions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(zeek_total_sessions_total[$__rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Analyzer Confirmations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(zeek_analyzer_confirmations_total{}[$__interval])",
     "legendFormat": "{{ kind }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Analyzer Violations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(zeek_analyzer_violations_total{}[$__interval])",
     "legendFormat": "{{ kind }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Event Handler Invocations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "expr": "rate(zeek_event_handler_invocations_total[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}