{
 "title": "ZeekOps Dashboard",
 "description": "A dashboard for Zeek operators.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(zeek_version_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage and Restarts",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (irate(process_cpu_user_seconds_total{job=\"$job\"}[$__rate_interval]) + irate(process_cpu_system_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(irate(process_cpu_user_seconds_total{job=\"$job\"}[$__rate_interval]) + irate(process_cpu_system_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "clamp_min(-5*changes(process_start_time_seconds{job=\"$job\"}[30s]), -10)",
     "legendFormat": "{{ node }} restarts "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node!=\"\", job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(zeek_net_dropped_packets_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "dropped packets"
    },
    {
     "expr": "sum(irate(zeek_net_link_packets_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "link packets"
    },
    {
     "expr": "max(zeek_net_packet_lag_seconds{job=\"$job\"})",
     "legendFormat": "max packet lag"
    },
    {
     "expr": "min(zeek_net_packet_lag_seconds{job=\"$job\"})",
     "legendFormat": "min packet lag"
    },
    {
     "expr": "avg(zeek_net_packet_lag_seconds{job=\"$job\"})",
     "legendFormat": "avg packet lag"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (protocol) (zeek_active_sessions{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Streams",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "logs/s" } },
   "targets": [
    {
     "expr": "sum by (stream) (irate(zeek_log_stream_writes_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Events/s",
   "type": "timeseries",
   "description": "Positive: Outgoing\nNegative: Incoming",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "-irate(zeek_cluster_core_incoming_events_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{node}} incoming total"
    },
    {
     "expr": "irate(zeek_cluster_core_outgoing_events_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ node }} outgoing total"
    }
   ]
  },
  {
   "title": "ZeroMQ Drops and Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "zeek_cluster_zeromq_onloop_drops_total{job=\"$job\"}",
     "legendFormat": "{{node}} {{__name__}}"
    },
    {
     "expr": "zeek_cluster_zeromq_xpub_drops_total{job=\"$job\"}",
     "legendFormat": "{{node}} {{__name__}}"
    },
    {
     "expr": "zeek_cluster_zeromq_msg_errors_total{job=\"$job\"}",
     "legendFormat": "{{node}} {{__name__}}"
    }
   ]
  },
  {
   "title": "Verbose Cluster Events/s",
   "type": "timeseries",
   "description": "Positive: Outgoing\nNegative: Incoming\n\nThis needs:\n```\nredef Cluster::Telemetry::core_metrics += {\n  Cluster::Telemetry::VERBOSE,\n};\n```",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "-irate(zeek_cluster_core_verbose_incoming_events_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{node}} incoming {{handler}} on {{ topic }}"
    },
    {
     "expr": "irate(zeek_cluster_core_verbose_outgoing_events_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{node}} outgoing {{handler}} on {{ topic }}"
    }
   ]
  }
 ]
}